Repository ecadlabs/taquito, pull requests merged in 2021-12, with the labels that each got.

#1244 updated rpc node list in docs
  docs/rpc_nodes.md
Labels: documentation

#1265 Mk 1248 changes to contracts collection
  docs/contract-test-collection.md
  docs/ledger_signer.md
  docs/transaction_limits.md
  example/data/contractOnChainViews.ts
  example/deploy-docs-live-code-contracts.ts
  example/deploy-integration-tests-contracts.ts
  website/yarn.lock
Labels: documentation, testing🧪

#1269 1268 website cloudflare pages deployments
  .github/workflows/deploy_website.yml
  .github/workflows/preview_website.yml
  package.json
  website/docs/batch-api.md
  website/docs/boilerplate.md
  website/docs/cancel_http_requests.md
  website/docs/complex_parameters.md
  website/docs/confirmation_event_stream.md
  website/docs/contract-test-collection.md
  website/docs/contracts-library.md
  website/docs/dapp_prelaunch.md
  website/docs/drain_account.md
  website/docs/estimate.md
  website/docs/fa2_parameters.md
  website/docs/global_constant.md
  website/docs/images/github.png
  website/docs/images/gitlab.png
  website/docs/inmemory_signer.md
  website/docs/lambda_view.md
  website/docs/ledger_integration_test.md
  website/docs/ledger_signer.md
  website/docs/making_transfers.md
  website/docs/maps_bigmaps.md
  website/docs/metadata-tzip16.md
  website/docs/michelson_encoder.md
  website/docs/michelsonmap.md
  website/docs/on_chain_views.md
  website/docs/originate.md
  website/docs/quick_start.md
  website/docs/rpc-cache.md
  website/docs/rpc_nodes.md
  website/docs/rpc_nodes_integration_test.md
  website/docs/rpc_package.md
  website/docs/set_delegate.md
  website/docs/signing.md
  website/docs/smartcontracts.md
  website/docs/storage_annotations.md
  website/docs/taquito_utils.md
  website/docs/tezbridge_signer.md
  website/docs/tezos_domains.md
  website/docs/tickets.md
  website/docs/transaction_limits.md
  website/docs/tutorial_links.md
  website/docs/tzip12.md
  website/docs/tzip16-sequence-diagram.md
  website/docs/upgrading_guide.md
  website/docs/validators.md
  website/docs/version.md
  website/docs/wallet_API.md
  website/docs/wallets.md
  website/docs/web3js_taquito.md
  website/docusaurus.config.js
  website/package.json
  website/yarn.lock
Labels: website
