Repository ecadlabs/taquito, pull requests merged in 2022-01, with the labels that each got.

#1285 redo the addition of split screen for storage in docs contract collection
  docs/contract-test-collection.md
Labels: documentation

#1310 Update to the README for the integration tests
  integration-tests/README.md
Labels: documentation, testing🧪

#1315 Mk 1294 deprecated sub instruction
  example/deploy-docs-live-code-contracts.ts
  integration-tests/contract-call-with-xtz-amount.spec.ts
  integration-tests/contract-sub-mutez.spec.ts
  integration-tests/contract-unit-as-param.spec.ts
  integration-tests/data/deposit_contract.ts
  integration-tests/data/deposit_contract_hangzhou.ts
  integration-tests/data/deposit_contract_ithaca.ts
  integration-tests/wallet-unit-as-param.spec.ts
  signature.json
Labels: bug, testing🧪

#1341 Update setup-node and cache GH actions to their latest versions and fix caching in pipelines
  .github/workflows/algolia.yml
  .github/workflows/deploy_edge.yml
  .github/workflows/deploy_website.yml
  .github/workflows/main.yml
  .github/workflows/preview_website.yml
  website/package-lock.json
  website/yarn.lock
Labels: ci/cd

#1345 Limit GH Action workflows concurrency
  .github/workflows/algolia.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy_edge.yml
  .github/workflows/deploy_website.yml
  .github/workflows/main.yml
  .github/workflows/preview_website.yml
Labels: ci/cd

#1350 Don't limit concurrency for pipelines triggered on master branch
  .github/workflows/algolia.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy_edge.yml
  .github/workflows/deploy_website.yml
  .github/workflows/main.yml
  .github/workflows/preview_website.yml
Labels: ci/cd

#1339 changed some integration tests file namesto suit pattern
  integration-tests/contract-call-method-manual-steps.spec.ts
  integration-tests/contract-deploy-having-global-constant-in-storage-part-script.spec.ts
  integration-tests/contract-edo-deploy-having-ticket.spec.ts
  integration-tests/contract-encode-long-numeral.spec.ts
  integration-tests/contract-lambda-view.spec.ts
  integration-tests/contract-manager-scenario.spec.ts
  integration-tests/contract-multisig-scenario.spec.ts
  integration-tests/contract-test-for-type-never.spec.ts
  integration-tests/delegate-call-get-when-no-delegate.spec.ts
  integration-tests/rpc-taquito.spec.ts
  integration-tests/wallet-edo-deploy-having-ticket.spec.ts
  integration-tests/wallet-manager-scenario.spec.ts
  integration-tests/wallet-multisig-scenario.spec.ts
Labels: testing-upgrade

#1338 Mk 1223 combine big map tests
  integration-tests/contract-big-map-access-by-index.spec.ts
  integration-tests/contract-big-map.spec.ts
  integration-tests/contract-fetch-multiple-big-map-keys.spec.ts
  integration-tests/contract-init-with-empty-bigmap.spec.ts
Labels: testing-upgrade

#1366 Remove Caching steps in Taquito workflows
  .github/workflows/deploy_edge.yml
  .github/workflows/deploy_website.yml
  .github/workflows/main.yml
  .github/workflows/preview_website.yml
Labels: ci/cd
